# Generated by Django 6.0.3 on 2026-04-06 22:11

import django.db.models.deletion
import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('words', '0002_seed_default_word_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='word_pack',
            field=models.ForeignKey(default=rooms.models.get_mvp_default_word_pack_id, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='words.wordpack'),
        ),
    ]
