# Generated by Django 6.0.3 on 2026-03-21 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "words",
                "ordering": ("text", "id"),
            },
        ),
        migrations.CreateModel(
            name="WordPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "word_lists",
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="WordPackEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "word",
                    models.ForeignKey(
                        db_column="word_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_pack_entries",
                        to="words.word",
                    ),
                ),
                (
                    "word_pack",
                    models.ForeignKey(
                        db_column="word_list_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_pack_entries",
                        to="words.wordpack",
                    ),
                ),
            ],
            options={
                "db_table": "word_list_entries",
                "ordering": ("word_pack_id", "word_id", "id"),
            },
        ),
        migrations.AddField(
            model_name="wordpack",
            name="words",
            field=models.ManyToManyField(related_name="packs", through="words.WordPackEntry", to="words.word"),
        ),
        migrations.AddConstraint(
            model_name="wordpackentry",
            constraint=models.UniqueConstraint(
                fields=("word_pack", "word"),
                name="uq_word_list_entries_word_list_word",
            ),
        ),
    ]
