# Generated by Django 6.0.3 on 2026-03-21 14:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("finished", "Finished"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="GameWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=255)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot_words",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "ordering": ("text", "id"),
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("drawer_nickname", models.CharField(max_length=24)),
                ("sequence_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("completed", "Completed"),
                            ("drawer_disconnected", "Drawer disconnected"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "drawer_participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drawn_rounds",
                        to="rooms.player",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="games.game",
                    ),
                ),
                (
                    "selected_game_word",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="round",
                        to="games.gameword",
                    ),
                ),
            ],
            options={
                "ordering": ("game_id", "sequence_number"),
            },
        ),
        migrations.CreateModel(
            name="Guess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=255)),
                ("typed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guesses",
                        to="rooms.player",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guesses",
                        to="games.round",
                    ),
                ),
            ],
            options={
                "ordering": ("round_id", "typed_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="gameword",
            constraint=models.UniqueConstraint(
                fields=("game", "text"),
                name="games_gameword_unique_game_text",
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                fields=("game", "sequence_number"),
                name="games_round_unique_game_sequence",
            ),
        ),
    ]
